# Generated by Django 4.2.3 on 2023-11-20 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_comentario_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoHabitacion",
            fields=[
                ("nombre", models.CharField(max_length=100)),
                (
                    "numero",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comentario",
            name="tipo_habitacion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.tipohabitacion",
            ),
        ),
    ]
